### MId Time ANN Model creation

Time --> 11 am to 4 pm 

In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv('../Datasets/traffic_light_mid_time.csv')
df.head()

,vehicles_N,vehicles_S,vehicles_E,vehicles_W,ped_N,ped_S,ped_E,ped_W,emg_N,emg_S,emg_E,emg_W,time_of_day,green_N,green_S,green_E,green_W,priority_order
0,35.0,34.0,17.0,39.0,1.0,0.0,1.0,1.0,3.0,0.0,2.0,3.0,1.0,137.068966,87.931034,77.586207,147.413793,WNSE
1,14.0,38.0,5.0,11.0,0.0,0.0,0.0,0.0,3.0,2.0,2.0,0.0,1.0,126.699029,209.708738,65.533981,48.058252,SNEW
2,4.0,16.0,5.0,13.0,1.0,0.0,0.0,0.0,3.0,0.0,2.0,2.0,1.0,130.263158,94.736842,88.815789,136.184211,WNSE
3,13.0,48.0,9.0,11.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,3.0,1.0,80.084746,194.491525,64.830508,110.593220,SWNE
4,5.0,35.0,4.0,27.0,1.0,0.0,1.0,1.0,0.0,3.0,0.0,0.0,1.0,37.894737,236.842105,33.157895,142.105263,SWNE


In [3]:
df.isnull().sum()

vehicles_N        0
vehicles_S        0
vehicles_E        0
vehicles_W        0
ped_N             0
ped_S             0
ped_E             0
ped_W             0
emg_N             0
emg_S             0
emg_E             0
emg_W             0
time_of_day       0
green_N           0
green_S           0
green_E           0
green_W           0
priority_order    0
dtype: int64

In [4]:
df.duplicated().sum()

np.int64(25056)

In [5]:
# Remove time_of_day column
df.drop(columns=['time_of_day','priority_order'],axis=1,inplace=True)
df.head()

,vehicles_N,vehicles_S,vehicles_E,vehicles_W,ped_N,ped_S,ped_E,ped_W,emg_N,emg_S,emg_E,emg_W,green_N,green_S,green_E,green_W
0,35.0,34.0,17.0,39.0,1.0,0.0,1.0,1.0,3.0,0.0,2.0,3.0,137.068966,87.931034,77.586207,147.413793
1,14.0,38.0,5.0,11.0,0.0,0.0,0.0,0.0,3.0,2.0,2.0,0.0,126.699029,209.708738,65.533981,48.058252
2,4.0,16.0,5.0,13.0,1.0,0.0,0.0,0.0,3.0,0.0,2.0,2.0,130.263158,94.736842,88.815789,136.184211
3,13.0,48.0,9.0,11.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,3.0,80.084746,194.491525,64.830508,110.593220
4,5.0,35.0,4.0,27.0,1.0,0.0,1.0,1.0,0.0,3.0,0.0,0.0,37.894737,236.842105,33.157895,142.105263


In [6]:
X=df.drop(columns=["green_N","green_S","green_E","green_W"])
Y=df[["green_N","green_S","green_E","green_W"]]

In [7]:
X

,vehicles_N,vehicles_S,vehicles_E,vehicles_W,ped_N,ped_S,ped_E,ped_W,emg_N,emg_S,emg_E,emg_W
0,35.0,34.0,17.0,39.0,1.0,0.0,1.0,1.0,3.0,0.0,2.0,3.0
1,14.0,38.0,5.0,11.0,0.0,0.0,0.0,0.0,3.0,2.0,2.0,0.0
2,4.0,16.0,5.0,13.0,1.0,0.0,0.0,0.0,3.0,0.0,2.0,2.0
3,13.0,48.0,9.0,11.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,3.0
4,5.0,35.0,4.0,27.0,1.0,0.0,1.0,1.0,0.0,3.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
49995,38.0,12.0,27.0,12.0,1.0,0.0,0.0,1.0,0.0,3.0,2.0,0.0
49996,46.0,38.0,28.0,43.0,0.0,1.0,1.0,1.0,2.0,1.0,0.0,3.0
49997,35.0,25.0,23.0,14.0,0.0,0.0,0.0,0.0,3.0,1.0,0.0,3.0
49998,3.0,18.0,13.0,24.0,0.0,0.0,1.0,0.0,0.0,2.0,2.0,2.0


In [8]:
Y

,green_N,green_S,green_E,green_W
0,137.068966,87.931034,77.586207,147.413793
1,126.699029,209.708738,65.533981,48.058252
2,130.263158,94.736842,88.815789,136.184211
3,80.084746,194.491525,64.830508,110.593220
4,37.894737,236.842105,33.157895,142.105263
...,...,...,...,...
49995,153.750000,101.250000,138.750000,56.250000
49996,129.896907,106.701031,71.907216,141.494845
49997,170.454545,102.272727,78.409091,98.863636
49998,14.835165,138.461538,128.571429,168.131868


In [9]:
# split test and training data
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=.2,random_state=42)

In [10]:
# stanrdization data for independent values
from sklearn.preprocessing import StandardScaler

mid_time_scalar_independent=StandardScaler()
X_train=mid_time_scalar_independent.fit_transform(X_train)
X_test=mid_time_scalar_independent.transform(X_test)

In [11]:
# stanrdization data for independent values
from sklearn.preprocessing import StandardScaler

mid_time_scalar_dependent=StandardScaler()
Y_train=mid_time_scalar_dependent.fit_transform(Y_train)
Y_test=mid_time_scalar_dependent.transform(Y_test)

In [12]:
# save StandardScaler models

import pickle

with open("../models/mid_time_models/mid_time_scaler_independent.pkl","wb") as file:
	pickle.dump(mid_time_scalar_independent,file)

with open("../models/mid_time_models/mid_time_scaler_dependent.pkl","wb") as file:
	pickle.dump(mid_time_scalar_dependent,file)

#### ANN Training 

In [13]:
import tensorflow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [14]:
# Model creation
mid_time_model = Sequential([
    Dense(64, input_dim=X_train.shape[1], activation='relu'),
    Dense(128, activation='relu'),
    Dense(64, activation='relu'),
    Dense(4, activation='linear')
])

In [15]:
mid_time_model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 128)            │         8,320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 4)              │           260 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 17,668 (69.02 KB)

 Trainable params: 17,668 (69.02 KB)

 Non-trainable params: 0 (0.00 B)

In [16]:
optimiser=tensorflow.keras.optimizers.Adam(learning_rate=.1)
loss=tensorflow.keras.losses.mse

In [17]:
mid_time_model.compile(optimizer=optimiser,loss=loss,metrics=['mae'])

In [18]:
# set up early stoping 
early_stopping_call_back=EarlyStopping(monitor='val_loss', patience=15, restore_best_weights=True)

In [19]:
# set up log files

log_dir="../logs/mid_time_log/fit/"+datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorBoard_callback=TensorBoard(log_dir=log_dir, histogram_freq=1)

In [20]:
mid_time_model.fit(
    X_train,
    Y_train,
    epochs=1000,
    validation_data=(X_test, Y_test),
    callbacks=[tensorBoard_callback, early_stopping_call_back]
)

Epoch 1/1000
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 1.6956 - mae: 0.8666 - val_loss: 1.0138 - val_mae: 0.8016
Epoch 2/1000
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 1.0059 - mae: 0.7975 - val_loss: 1.0199 - val_mae: 0.8041
Epoch 3/1000
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 1.0039 - mae: 0.7968 - val_loss: 1.0400 - val_mae: 0.8115
Epoch 4/1000
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 1.0136 - mae: 0.8011 - val_loss: 1.0315 - val_mae: 0.8091
Epoch 5/1000
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 1.0152 - mae: 0.8022 - val_loss: 1.0147 - val_mae: 0.8018
Epoch 6/1000
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 1.0148 - mae: 0.8025 - val_loss: 1.0282 - val_mae: 0.8076
Epoch 7/1000
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 1.0008 - mae: 0.7948 - val_loss: 1.0289 - val_mae: 0.8074
Epoch 8/1000
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 1.0025 - mae: 0.7962 - val_loss: 1.0173 - val_mae: 0.8030
Epoch 9/1000
1250/1250 ━

In [21]:
mid_time_model.metrics

[<Mean name=loss>, <CompileMetrics name=compile_metrics>]

In [22]:
results = mid_time_model.evaluate(X_test, Y_test, return_dict=True)
print(results)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1.0196 - mae: 0.8050
{'loss': 1.0117617845535278, 'mae': 0.8005613088607788}


In [23]:
input_data = pd.DataFrame([{
    'vehicles_N': 50,
    'vehicles_S': 30,
    'vehicles_E': 60,
    'vehicles_W': 40,
    'ped_N': 1,
    'ped_S': 0,
    'ped_E': 1,
    'ped_W': 0,
    'emg_N': 2,
    'emg_S': 0,
    'emg_E': 1,
    'emg_W': 0,
}])
input_data

,vehicles_N,vehicles_S,vehicles_E,vehicles_W,ped_N,ped_S,ped_E,ped_W,emg_N,emg_S,emg_E,emg_W
0,50,30,60,40,1,0,1,0,2,0,1,0


In [24]:
input_data_scalar=mid_time_scalar_independent.transform(input_data)
input_data_scalar

array([[ 1.15475457,  0.10004136,  1.6774044 ,  0.62277443,  0.99193254,
        -0.99133752,  0.9938688 , -1.01121286,  0.44741039, -1.3630607 ,
        -0.4494281 , -1.33183606]])

In [25]:
pred=mid_time_model.predict(input_data_scalar)
pred[0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step


array([ 0.01014232, -0.00937318, -0.00158219, -0.00269681], dtype=float32)

In [26]:
input_data

,vehicles_N,vehicles_S,vehicles_E,vehicles_W,ped_N,ped_S,ped_E,ped_W,emg_N,emg_S,emg_E,emg_W
0,50,30,60,40,1,0,1,0,2,0,1,0


In [27]:
normal_value=mid_time_scalar_dependent.inverse_transform(pred)
normal_value

array([[112.263245, 112.509224, 112.2498  , 112.807205]], dtype=float32)

In [29]:
mid_time_model.save('../models/mid_time_models/mid_time_model.h5')