### Morning Time ANN Model creation

Time --> 6:30 am to 11 pm 

In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv('../Datasets/traffic_light_morning_time.csv')
df.head()

,vehicles_N,vehicles_S,vehicles_E,vehicles_W,ped_N,ped_S,ped_E,ped_W,emg_N,emg_S,emg_E,emg_W,time_of_day,green_N,green_S,green_E,green_W,priority_order
0,3.0,11.0,48.0,41.0,0.0,1.0,1.0,0.0,2.0,2.0,2.0,2.0,0.0,19.630872,36.241611,92.114094,77.013423,EWSN
1,2.0,25.0,46.0,11.0,1.0,0.0,1.0,0.0,3.0,1.0,1.0,2.0,0.0,36.000000,54.000000,97.200000,37.800000,ESWN
2,38.0,9.0,15.0,13.0,0.0,1.0,0.0,1.0,0.0,2.0,3.0,1.0,0.0,77.027027,44.594595,60.810811,42.567568,NESW
3,41.0,7.0,25.0,16.0,0.0,0.0,0.0,0.0,2.0,1.0,3.0,3.0,0.0,85.634328,20.149254,67.164179,52.052239,NEWS
4,16.0,15.0,31.0,5.0,0.0,0.0,1.0,0.0,0.0,2.0,3.0,0.0,0.0,37.894737,59.210526,116.052632,11.842105,ESNW


In [3]:
df.isnull().sum()

vehicles_N        0
vehicles_S        0
vehicles_E        0
vehicles_W        0
ped_N             0
ped_S             0
ped_E             0
ped_W             0
emg_N             0
emg_S             0
emg_E             0
emg_W             0
time_of_day       0
green_N           0
green_S           0
green_E           0
green_W           0
priority_order    0
dtype: int64

In [4]:
df.duplicated().sum()

np.int64(40146)

In [5]:
# Remove time_of_day column
df.drop(columns=['time_of_day','priority_order'],axis=1,inplace=True)
df.head()

,vehicles_N,vehicles_S,vehicles_E,vehicles_W,ped_N,ped_S,ped_E,ped_W,emg_N,emg_S,emg_E,emg_W,green_N,green_S,green_E,green_W
0,3.0,11.0,48.0,41.0,0.0,1.0,1.0,0.0,2.0,2.0,2.0,2.0,19.630872,36.241611,92.114094,77.013423
1,2.0,25.0,46.0,11.0,1.0,0.0,1.0,0.0,3.0,1.0,1.0,2.0,36.000000,54.000000,97.200000,37.800000
2,38.0,9.0,15.0,13.0,0.0,1.0,0.0,1.0,0.0,2.0,3.0,1.0,77.027027,44.594595,60.810811,42.567568
3,41.0,7.0,25.0,16.0,0.0,0.0,0.0,0.0,2.0,1.0,3.0,3.0,85.634328,20.149254,67.164179,52.052239
4,16.0,15.0,31.0,5.0,0.0,0.0,1.0,0.0,0.0,2.0,3.0,0.0,37.894737,59.210526,116.052632,11.842105


In [6]:
X=df.drop(columns=["green_N","green_S","green_E","green_W"])
Y=df[["green_N","green_S","green_E","green_W"]]

In [7]:
X

,vehicles_N,vehicles_S,vehicles_E,vehicles_W,ped_N,ped_S,ped_E,ped_W,emg_N,emg_S,emg_E,emg_W
0,3.0,11.0,48.0,41.0,0.0,1.0,1.0,0.0,2.0,2.0,2.0,2.0
1,2.0,25.0,46.0,11.0,1.0,0.0,1.0,0.0,3.0,1.0,1.0,2.0
2,38.0,9.0,15.0,13.0,0.0,1.0,0.0,1.0,0.0,2.0,3.0,1.0
3,41.0,7.0,25.0,16.0,0.0,0.0,0.0,0.0,2.0,1.0,3.0,3.0
4,16.0,15.0,31.0,5.0,0.0,0.0,1.0,0.0,0.0,2.0,3.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
49995,38.0,27.0,44.0,17.0,1.0,0.0,0.0,0.0,3.0,3.0,1.0,1.0
49996,13.0,27.0,42.0,25.0,1.0,0.0,1.0,1.0,1.0,2.0,2.0,3.0
49997,1.0,41.0,36.0,17.0,0.0,1.0,1.0,1.0,3.0,3.0,0.0,2.0
49998,16.0,31.0,21.0,36.0,1.0,1.0,0.0,0.0,1.0,3.0,0.0,0.0


In [8]:
Y

,green_N,green_S,green_E,green_W
0,19.630872,36.241611,92.114094,77.013423
1,36.000000,54.000000,97.200000,37.800000
2,77.027027,44.594595,60.810811,42.567568
3,85.634328,20.149254,67.164179,52.052239
4,37.894737,59.210526,116.052632,11.842105
...,...,...,...,...
49995,74.556213,55.917160,65.236686,29.289941
49996,30.288462,53.365385,79.326923,62.019231
49997,25.000000,92.187500,60.937500,46.875000
49998,41.538462,84.807692,36.346154,62.307692


In [9]:
# split test and training data
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=.2,random_state=15)

In [10]:
# stanrddization data for independent values
from sklearn.preprocessing import StandardScaler

morning_time_scalar_independent=StandardScaler()
X_train=morning_time_scalar_independent.fit_transform(X_train)
X_test=morning_time_scalar_independent.transform(X_test)

In [11]:
# stanrddization data for independent values
from sklearn.preprocessing import StandardScaler

morning_time_scalar_dependent=StandardScaler()
Y_train=morning_time_scalar_dependent.fit_transform(Y_train)
Y_test=morning_time_scalar_dependent.transform(Y_test)

In [12]:
# save StandardScaler models

import pickle

with open("../models/morning_time_models/morning_time_scaler_independent.pkl","wb") as file:
	pickle.dump(morning_time_scalar_independent,file)

with open("../models/morning_time_models/morning_time_scaler_dependent.pkl","wb") as file:
	pickle.dump(morning_time_scalar_dependent,file)

### ANN Training

In [13]:
import tensorflow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [14]:
# Model creation
morning_time_model = Sequential([
    Dense(64, input_dim=X_train.shape[1], activation='relu'),
    Dense(128, activation='relu'),
    Dense(64, activation='relu'),
    Dense(4, activation='linear')
])

In [15]:
morning_time_model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 128)            │         8,320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 4)              │           260 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 17,668 (69.02 KB)

 Trainable params: 17,668 (69.02 KB)

 Non-trainable params: 0 (0.00 B)

In [16]:
optimiser=tensorflow.keras.optimizers.Adam(learning_rate=.1)
loss=tensorflow.keras.losses.mse

In [17]:
# set optimisers , loss functions
morning_time_model.compile(optimizer=optimiser,loss=loss,metrics=['mae'])

In [18]:
# set up early stoping 
early_stopping_call_back=EarlyStopping(monitor='val_loss', patience=15, restore_best_weights=True)

In [19]:
# set up log files

log_dir="../logs/morning_time_log/fit/"+datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorBoard_callback=TensorBoard(log_dir=log_dir, histogram_freq=1)

In [20]:
morning_time_model.fit(
    X_train,
    Y_train,
    epochs=1000,
    validation_data=(X_test, Y_test),
    callbacks=[tensorBoard_callback, early_stopping_call_back]
)

Epoch 1/1000
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 1.0013 - mae: 0.5439 - val_loss: 0.0332 - val_mae: 0.1416
Epoch 2/1000
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 0.0353 - mae: 0.1426 - val_loss: 0.0307 - val_mae: 0.1293
Epoch 3/1000
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 0.0459 - mae: 0.1612 - val_loss: 0.0336 - val_mae: 0.1320
Epoch 4/1000
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 0.0568 - mae: 0.1785 - val_loss: 0.1141 - val_mae: 0.2667
Epoch 5/1000
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 0.0555 - mae: 0.1760 - val_loss: 0.0383 - val_mae: 0.1492
Epoch 6/1000
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 0.0452 - mae: 0.1621 - val_loss: 0.0788 - val_mae: 0.2343
Epoch 7/1000
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 0.0663 - mae: 0.1952 - val_loss: 0.0397 - val_mae: 0.1530
Epoch 8/1000
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 0.0487 - mae: 0.1678 - val_loss: 0.0481 - val_mae: 0.1731
Epoch 9/1000
1250/1250 

In [21]:
morning_time_model.metrics

[<Mean name=loss>, <CompileMetrics name=compile_metrics>]

In [22]:
results = morning_time_model.evaluate(X_test, Y_test, return_dict=True)
print(results)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0309 - mae: 0.1298
{'loss': 0.030723830685019493, 'mae': 0.1292712539434433}


In [23]:
input_data = pd.DataFrame([{
    'vehicles_N': 50,
    'vehicles_S': 30,
    'vehicles_E': 60,
    'vehicles_W': 40,
    'ped_N': 1,
    'ped_S': 0,
    'ped_E': 1,
    'ped_W': 0,
    'emg_N': 2,
    'emg_S': 0,
    'emg_E': 1,
    'emg_W': 0,
}])
input_data

,vehicles_N,vehicles_S,vehicles_E,vehicles_W,ped_N,ped_S,ped_E,ped_W,emg_N,emg_S,emg_E,emg_W
0,50,30,60,40,1,0,1,0,2,0,1,0


In [24]:
input_data_scalar=morning_time_scalar_independent.transform(input_data)
input_data_scalar

array([[ 1.17997321,  0.10900456,  1.72664167,  0.6590933 ,  0.98343714,
        -1.0036065 ,  0.99094103, -0.99595817,  0.44691797, -1.34547122,
        -0.45142452, -1.34439629]])

In [25]:
pred=morning_time_model.predict(input_data_scalar)
pred[0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step


array([ 0.44814134, -0.84575474,  0.77252364, -0.36111778], dtype=float32)

In [26]:
input_data

,vehicles_N,vehicles_S,vehicles_E,vehicles_W,ped_N,ped_S,ped_E,ped_W,emg_N,emg_S,emg_E,emg_W
0,50,30,60,40,1,0,1,0,2,0,1,0


In [27]:
normal_value=morning_time_scalar_dependent.inverse_transform(pred)
normal_value

array([[67.13578 , 36.305878, 74.32538 , 47.372257]], dtype=float32)

In [28]:
morning_time_model.save('../models/morning_time_models/morning_time_model.h5')