### Night Time ANN Model creation

Time --> 4:30 am to 8 pm 

In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv('../Datasets/traffic_light_night_time.csv')
df.head()

,vehicles_N,vehicles_S,vehicles_E,vehicles_W,ped_N,ped_S,ped_E,ped_W,emg_N,emg_S,emg_E,emg_W,time_of_day,green_N,green_S,green_E,green_W,priority_order
0,29.0,36.0,6.0,43.0,0.0,1.0,1.0,1.0,2.0,0.0,0.0,1.0,2.0,190.760870,190.760870,44.021739,249.456522,WNSE
1,7.0,44.0,21.0,1.0,0.0,0.0,0.0,0.0,2.0,2.0,3.0,0.0,2.0,106.250000,337.500000,225.000000,6.250000,SENW
2,5.0,0.0,38.0,18.0,0.0,1.0,1.0,0.0,3.0,1.0,0.0,3.0,2.0,132.352941,52.941176,271.323529,218.382353,EWNS
3,27.0,30.0,13.0,15.0,1.0,1.0,1.0,1.0,2.0,2.0,3.0,3.0,2.0,183.673469,197.448980,142.346939,151.530612,SNWE
4,21.0,40.0,24.0,5.0,0.0,1.0,0.0,0.0,1.0,2.0,2.0,2.0,2.0,137.109375,279.492188,179.296875,79.101562,SENW


In [3]:
df.isnull().sum()

vehicles_N        0
vehicles_S        0
vehicles_E        0
vehicles_W        0
ped_N             0
ped_S             0
ped_E             0
ped_W             0
emg_N             0
emg_S             0
emg_E             0
emg_W             0
time_of_day       0
green_N           0
green_S           0
green_E           0
green_W           0
priority_order    0
dtype: int64

In [4]:
df.duplicated().sum()

np.int64(35383)

In [5]:
# Remove time_of_day column
df.drop(columns=['time_of_day','priority_order'],axis=1,inplace=True)
df.head()

,vehicles_N,vehicles_S,vehicles_E,vehicles_W,ped_N,ped_S,ped_E,ped_W,emg_N,emg_S,emg_E,emg_W,green_N,green_S,green_E,green_W
0,29.0,36.0,6.0,43.0,0.0,1.0,1.0,1.0,2.0,0.0,0.0,1.0,190.760870,190.760870,44.021739,249.456522
1,7.0,44.0,21.0,1.0,0.0,0.0,0.0,0.0,2.0,2.0,3.0,0.0,106.250000,337.500000,225.000000,6.250000
2,5.0,0.0,38.0,18.0,0.0,1.0,1.0,0.0,3.0,1.0,0.0,3.0,132.352941,52.941176,271.323529,218.382353
3,27.0,30.0,13.0,15.0,1.0,1.0,1.0,1.0,2.0,2.0,3.0,3.0,183.673469,197.448980,142.346939,151.530612
4,21.0,40.0,24.0,5.0,0.0,1.0,0.0,0.0,1.0,2.0,2.0,2.0,137.109375,279.492188,179.296875,79.101562


In [6]:
X=df.drop(columns=["green_N","green_S","green_E","green_W"])
Y=df[["green_N","green_S","green_E","green_W"]]

In [7]:
X

,vehicles_N,vehicles_S,vehicles_E,vehicles_W,ped_N,ped_S,ped_E,ped_W,emg_N,emg_S,emg_E,emg_W
0,29.0,36.0,6.0,43.0,0.0,1.0,1.0,1.0,2.0,0.0,0.0,1.0
1,7.0,44.0,21.0,1.0,0.0,0.0,0.0,0.0,2.0,2.0,3.0,0.0
2,5.0,0.0,38.0,18.0,0.0,1.0,1.0,0.0,3.0,1.0,0.0,3.0
3,27.0,30.0,13.0,15.0,1.0,1.0,1.0,1.0,2.0,2.0,3.0,3.0
4,21.0,40.0,24.0,5.0,0.0,1.0,0.0,0.0,1.0,2.0,2.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...
49995,33.0,4.0,22.0,43.0,0.0,0.0,1.0,0.0,0.0,3.0,2.0,0.0
49996,18.0,11.0,18.0,34.0,1.0,1.0,0.0,1.0,3.0,2.0,2.0,3.0
49997,3.0,13.0,18.0,38.0,0.0,0.0,1.0,1.0,2.0,0.0,0.0,1.0
49998,8.0,26.0,19.0,39.0,1.0,1.0,1.0,0.0,2.0,3.0,3.0,3.0


In [8]:
Y

,green_N,green_S,green_E,green_W
0,190.760870,190.760870,44.021739,249.456522
1,106.250000,337.500000,225.000000,6.250000
2,132.352941,52.941176,271.323529,218.382353
3,183.673469,197.448980,142.346939,151.530612
4,137.109375,279.492188,179.296875,79.101562
...,...,...,...,...
49995,171.346154,98.653846,181.730769,223.269231
49996,173.571429,115.714286,135.000000,250.714286
49997,94.354839,94.354839,152.419355,333.870968
49998,90.865385,190.384615,160.096154,233.653846


In [9]:
# split test and training data
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=.2,random_state=42)

In [10]:
# stanrdization data for independent values
from sklearn.preprocessing import StandardScaler

night_time_scalar_independent=StandardScaler()
X_train=night_time_scalar_independent.fit_transform(X_train)
X_test=night_time_scalar_independent.transform(X_test)

In [11]:
# stanrdization data for independent values
from sklearn.preprocessing import StandardScaler

night_time_scalar_dependent=StandardScaler()
Y_train=night_time_scalar_dependent.fit_transform(Y_train)
Y_test=night_time_scalar_dependent.transform(Y_test)

In [12]:
# save StandardScaler models

import pickle

with open("../models/night_time_models/night_time_scaler_independent.pkl","wb") as file:
	pickle.dump(night_time_scalar_independent,file)

with open("../models/night_time_models/night_time_scaler_dependent.pkl","wb") as file:
	pickle.dump(night_time_scalar_dependent,file)

#### ANN Training 

In [13]:
import tensorflow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [14]:
# Model creation
night_time_model = Sequential([
    Dense(64, input_dim=X_train.shape[1], activation='relu'),
    Dense(128, activation='relu'),
    Dense(64, activation='relu'),
    Dense(4, activation='linear')
])

In [15]:
night_time_model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 128)            │         8,320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 4)              │           260 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 17,668 (69.02 KB)

 Trainable params: 17,668 (69.02 KB)

 Non-trainable params: 0 (0.00 B)

In [16]:
optimiser=tensorflow.keras.optimizers.Adam(learning_rate=.1)
loss=tensorflow.keras.losses.mse

In [17]:
night_time_model.compile(optimizer=optimiser,loss=loss,metrics=['mae'])

In [18]:
# set up early stoping 
early_stopping_call_back=EarlyStopping(monitor='val_loss', patience=15, restore_best_weights=True)

In [19]:
# set up log files

log_dir="../logs/night_time_log/fit/"+datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorBoard_callback=TensorBoard(log_dir=log_dir, histogram_freq=1)

In [20]:
night_time_model.fit(
    X_train,
    Y_train,
    epochs=1000,
    validation_data=(X_test, Y_test),
    callbacks=[tensorBoard_callback, early_stopping_call_back]
)

Epoch 1/1000
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 1.5208 - mae: 0.6340 - val_loss: 0.3563 - val_mae: 0.4138
Epoch 2/1000
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 0.3609 - mae: 0.4064 - val_loss: 0.0367 - val_mae: 0.1401
Epoch 3/1000
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 0.0421 - mae: 0.1533 - val_loss: 0.0291 - val_mae: 0.1343
Epoch 4/1000
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 0.0399 - mae: 0.1510 - val_loss: 0.0329 - val_mae: 0.1384
Epoch 5/1000
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 0.0539 - mae: 0.1726 - val_loss: 0.0382 - val_mae: 0.1495
Epoch 6/1000
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 0.0506 - mae: 0.1708 - val_loss: 0.0258 - val_mae: 0.1212
Epoch 7/1000
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 0.0473 - mae: 0.1655 - val_loss: 0.0494 - val_mae: 0.1713
Epoch 8/1000
1250/1250 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 0.0492 - mae: 0.1677 - val_loss: 0.0750 - val_mae: 0.2113
Epoch 9/1000
1250/1250 ━

In [21]:
night_time_model.metrics

[<Mean name=loss>, <CompileMetrics name=compile_metrics>]

In [22]:
results = night_time_model.evaluate(X_test, Y_test, return_dict=True)
print(results)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0255 - mae: 0.1207
{'loss': 0.025839826092123985, 'mae': 0.12117484211921692}


In [23]:
input_data = pd.DataFrame([{
    'vehicles_N': 50,
    'vehicles_S': 30,
    'vehicles_E': 60,
    'vehicles_W': 40,
    'ped_N': 1,
    'ped_S': 0,
    'ped_E': 1,
    'ped_W': 0,
    'emg_N': 2,
    'emg_S': 0,
    'emg_E': 1,
    'emg_W': 0,
}])
input_data

,vehicles_N,vehicles_S,vehicles_E,vehicles_W,ped_N,ped_S,ped_E,ped_W,emg_N,emg_S,emg_E,emg_W
0,50,30,60,40,1,0,1,0,2,0,1,0


In [24]:
input_data_scalar=night_time_scalar_independent.transform(input_data)
input_data_scalar

array([[ 1.18398324,  0.12242136,  1.678119  ,  0.64777607,  0.99431615,
        -0.9995501 ,  0.98324042, -1.00150113,  0.45514657, -1.33023126,
        -0.4550829 , -1.33698663]])

In [25]:
pred=night_time_model.predict(input_data_scalar)
pred[0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step


array([ 0.54387283, -0.88664067,  0.83264685, -0.4827791 ], dtype=float32)

In [26]:
input_data

,vehicles_N,vehicles_S,vehicles_E,vehicles_W,ped_N,ped_S,ped_E,ped_W,emg_N,emg_S,emg_E,emg_W
0,50,30,60,40,1,0,1,0,2,0,1,0


In [27]:
normal_value=night_time_scalar_dependent.inverse_transform(pred)
normal_value

array([[205.94456, 104.59212, 230.07376, 134.34286]], dtype=float32)

In [28]:
night_time_model.save('../models/night_time_models/night_time_model.h5')